# TODO: convert config into YAML format
# FIXME: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in a future release. Use .Site.Params instead.

# FIXME: baseURL n'est pas pris en compte pour les images des posts
# baseURL is used to build the full URL path of Web links
baseURL: https://1313-lpiot-gitpodworkspace-1ik5jt7i7s6.ws-eu116.gitpod.io

title: Ugloo
author: Ludovic Piot
copyright: ©2024, Ugloo.

timeZone: Europe/Paris

theme: hugo-bootstrap-theme
themesdir: themes/

disableHugoGeneratorInject: false
enableRobotsTXT: true
#enableGitInfo: true
enableEmoji: true
#sectionPagesMenu: main
#googleAnalytics: UA-1511XXXX-X

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - lastmod
    - :fileModTime
    - :default

# ----- LANGUAGES
# isMultilingual
defaultContentLanguage: fr
defaultContentLanguageInSubdir: false

fr:
  languageName: 🇫🇷 Français
  languageCode: fr-FR
  weight: 10
  params:
    languageISO: 🇫🇷

en:
  languageName: 🇺🇸 English
  languageCode: en-US
  weight: 20
  params:
    languageISO: 🇺🇸

taxonomies:
  tag: tags
  category: categories
  feature-tag: feature-tags
  # feature: features
  # event: events
  # series: series
  # author: authors

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

permalinks:
  post: /post/:title/
  feature: /feature/:title/
  event: /event/:title/

module:
  hugoVersion:
    extended: true
    min: 0.320.0
    max: 
  mounts:
    - source: assets
      target: assets
    - source: static
      target: static
