fr:
  languageName: 🇫🇷 Français
  languageCode: fr-FR
  weight: 10
  params:
    languageISO: 🇫🇷
    description: Stockage objet 🇫🇷 compatible AWS S3, indestructible, illimité et distribué

en:
  languageName: 🇺🇸 English
  languageCode: en-US
  weight: 20
  params:
    languageISO: 🇺🇸
    description: AWS S3 compatible object storage 🇫🇷, infinite-scaling, indestructible, distributed
