[fr]
  languageName = "🇫🇷 Français"
  languageCode = "fr-FR"
  weight = 10
  [fr.params]
    languageISO = "🇫🇷"

[en]
  languageName = "🇺🇸 English"
  languageCode = "en-US"
  weight = 20
  [en.params]
    languageISO = "🇺🇸"
