image:
  # This image is built upon the following Dockerfile: .gitpod.Dockerfile
  gitpod/workspace-go
  # You can dynamically build the image when you create a new GitPod workspace with the following lines
  # gitpod/workspace-full
  # file: .gitpod.Dockerfile

tasks:
  - name: workspace configuration
    command: |
      wget https://github.com/gohugoio/hugo/releases/download/v0.127.0/hugo_extended_0.127.0_Linux-64bit.tar.gz
      gunzip ./hugo_extended_0.127.0_Linux-64bit.tar.gz
      tar -xf ./hugo_extended_0.127.0_Linux-64bit.tar
      sudo mv ./hugo /usr/local/bin/      

vscode:
  extensions:
    - yzhang.markdown-all-in-one
    - Gruntfuggly.todo-tree

workspaceLocation:
  "."
