[[main]]
name = "The Company"
url = "about"
weight = 10
title = "Welcome at Ugloo office"

# ----- Submenu NEEDS
# TODO: create a page about DATA needs?
# [[main]]
# identifier = "data needs"
# name = "An answer to data needs"
# url = "data needs"
# weight = 20

# ----- Submenu PROS
[[main]]
identifier = "pros"
name = "Pros"
url = "pros"
weight = 30
title="Learn more about most pros of Ugloo software"

# ----- Submenu FEATURES
[[main]]
identifier = "features"
name = "Features"
url = "features"
weight = 40
title="Learn more details about Ugloo main features"

# ----- Submenu EVENTS
[[main]]
identifier = "events"
name = "Events & press"
url = "events"
weight = 50
title="Read latest news about Ugloo"

# ----- Submenu BLOG
# TODO: create a BLOG section
# [[main]]
# identifier = "blog"
# name = "Posts"
# weight = 60

# ----- Submenu SOCIAL
[[social]]
[[social]]
  name = "LinkedIn - Ugloo"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='../images/feather/feather-sprite.svg#linkedin'/></svg>"
  url = "https://www.linkedin.com/company/ugloo/posts/?feedView=all"
  weight = 10
  title = "Ugloo's LinkedIn page"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-twitter'><use href='../images/feather/feather-sprite.svg#github'/></svg>"
  url = "https://github.com/ugloo"
  weight = 20
  title = "Github organisation"

[[social]]
  name = "LinkedIn - Gonzague"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='../images/feather/feather-sprite.svg#linkedin'/></svg>"
  url = "https://www.linkedin.com/in/gonzaguedupont/recent-activity/all/"
  weight = 30
  title = "Gonzague Dupont's LinkedIn page"

