[[main]]
name = "La société"
url = "about"
weight = 10
title = "Bienvenue au sein des locaux Ugloo"

# ----- Sous-menu NEEDS
# TODO: ouvrir une page sur les besoins en DATA ?
# [[main]]
# identifier = "data needs"
# name = "Une réponse aux besoins"
# url = "data needs"
# weight = 20

# ----- Sous-menu PROS
[[main]]
identifier = "pros"
name = "Les avantages"
url = "pros"
weight = 30
title = "Découvrez les principaux avantages de la solution"

# ----- Sous-menu FEATURES
[[main]]
identifier = "features"
name = "La solution"
url = "features"
weight = 40
title = "Détail des fonctionnalités de la solution"

# ----- Sous-menu EVENTS
[[main]]
identifier = "events"
name = "On parle d'Ugloo"
url = "events"
weight = 50
title = "Les dernières nouvelles autour d'Ugloo"

# ----- Sous-menu BLOG
# TODO: ouvrir la section BLOG
# [[main]]
# identifier = "blog"
# name = "Blog"
# weight = 60

# [[main]]
# name = "Articles tech"
# url = "tags/tech"
# weight = 62
# parent = "blog"

# [[main]]
# name = "Tout"
# url = "posts"
# weight = 100
# parent = "blog"

# ----- Sous-menu SOCIAL
[[social]]
  name = "GitHub"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='/images/feather/feather-sprite.svg#linkedin'/></svg>"
  url = "https://github.com/filipecarneiro/hugo-bootstrap-theme/"
  weight = 10
  title = "Visit the GitHub project"

[[social]]
  name = "Twitter"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-twitter'><use href='/images/feather/feather-sprite.svg#twitter'/></svg>"
  url = "https://twitter.com/jfilipecarneiro/"
  weight = 20
  title = "Contact on Twitter/X"
